### PR TITLE
Added countries fron 11-20

### PR DESCRIPTION
**Pull request by SamantaTarun**
Screenshot at 2022-12-26 15-05-44

@tarunsamanta2k20

### CODE REVIEW

**Comment by VectorChi** [comment]
Prime Minister of Bahamas is Philip Davis. Ingraham is the former.

**Comment by VectorChi** [comment]
Same with Belize. The current Prime Minister is Johnny Briceño

**Comment by VectorChi** [comment]
Prime Minister of Belgium is Alexander De Croo

**Comment by SamantaTarun** [comment]
Okay making all those changes

**Comment by SamantaTarun** [comment]
@VectorChi  Done.

**Pull request merged**
