### PR TITLE
Mobile Screen Responsive.

### LINKED ISSUE #48: Add responsiveness
It doesn't need to be perfect.

For guide

```
@media (min-width:320px)  { /* smartphones, iPhone, portrait 480x320 phones */ }
@media (min-width:481px)  { /* portrait e-readers (Nook/Kindle), smaller tablets @ 600 or @ 640 wide. */ }
@media (min-width:641px)  { /* portrait tablets, portrait iPad, landscape e-readers, landscape 800x480 or 854x480 phones */ }
@media (min-width:961px)  { /* tablet, landscape iPad, lo-res laptops ands desktops */ }
@media (min-width:1025px) { /* big landscape tablets, laptops, and desktops */ }
@media (min-width:1281px) { /* hi-res laptops and desktops */ }
```

### PR DESCRIPTION
**Pull request by Rishav1707**
## This PR closes the following issue:
closes #48 

## Changes made:
- Added media query for the small screen.
- Added media query for the medium screen.
- Added media query for the large screen.

## Screenshots:
https://clipchamp.com/watch/YMabnz7fe8a

### CODE REVIEW

**Comment by VectorChi** [comment]
Hi @Rishav1707, Kindly update your branch and make another commit.

**Comment by Rishav1707** [comment]
> Hi @Rishav1707, Kindly update your branch and make another commit.

The branch is already updated in responsive.

**Comment by VectorChi** [comment]
Not yet. Check [live](https://vectorchi.github.io/worldpresidents/) link.

**Comment by Rishav1707** [comment]
> Hi @Rishav1707, Kindly update your branch and make another commit.

Can you help me how to update the branch?

**Comment by Rishav1707** [comment]
> Hi @Rishav1707, Kindly update your branch and make another commit.

Done @VectorChi

**Pull request merged**
