### PR TITLE
feat: add contributors.html page

### PR DESCRIPTION
**Pull request by agung2001**
## Fixes Issue

- #53 

## Note to reviewers

- I just added the `contributors.html` page with `contributors.json` to make it easier to add contributors.

### CODE REVIEW

**Comment by VectorChi** [comment]
Is there a link from `index.html` to this page

**Comment by agung2001** [comment]
not yet, do u want me to add it?

**Comment by VectorChi** [comment]
Yeah. A way for visitors outside Github to see the page

**Comment by agung2001** [comment]
ok, It's added now. It's positioned before the moon icon in the nav bar.
If you like it, maybe consider merging the changes 😄👍

**Comment by VectorChi** [comment]
Thanks. Is there a reason for moving the search functionality JS logic to `index.html`?

**Comment by agung2001** [comment]
because if you still put the `searchInput` function in `main.js` it will throw an error.
the error caused by `#search` is not present in `contributors.html`

`main.js` is included in both `index.html` and `contributors.html`,
because both files needed to be able to change the theme `dark/light`and the function is stored in `toggleIcon`

**Comment by VectorChi** [comment]
I don't fully understand. Kindly deploy on your branch and share a link

**Comment by agung2001** [comment]
ok to avoid confusion I've reverted back the `main.js` to its original version

**Comment by VectorChi** [comment]
Seen. I'll investigate more after I merge

**Pull request merged**
